!create autor1 : Autor
!create livro1 : Livro
!set livro1.titulo := 'Introducao a UML'
!set livro1.preco := 150.0
!set livro1.prazo := 4
!set livro1.quantidade_estoque := 10
!set livro1.disponibilidade := true
!create editor1 : Editor
!create grafica1 : Grafica
!create dataContrato : Date
!set dataContrato.dia := 30
!set dataContrato.mes := 6
!set dataContrato.ano := 2012
!create contrato1 : Contrato_Direitos_Autorais
!set contrato1.prazo_validade := dataContrato
!create dataPedido : Date
!set dataPedido.dia := 30
!set dataPedido.mes := 6
!set dataPedido.ano := 2011
!create pedido1 : PedidoCompra
!set pedido1.formaEnvio := 'expresso'
!set pedido1.dataPedido := dataPedido
!create dataEntrega1 : Date
!set dataEntrega1.dia := 30
!set dataEntrega1.mes := 6
!set dataEntrega1.ano := 2010
!create entrega1 : Entrega
!set entrega1.data := dataEntrega1
!create pagamento1 : Pagamento
!create livreiro1 : Livreiro
!set livreiro1.cidade := 'Rio de Janeiro'
!create devolucao1 : SolicitacaoDevolucao
!set devolucao1.analizada := true
!set devolucao1.autorizada := true
!create dataFatura : Date
!set dataFatura.dia := 1
!set dataFatura.mes := 2
!set dataFatura.ano := 2012
!create fatura1 : Fatura
!set fatura1.formaPagamento := 'boleto'
!set fatura1.prazoPagamento := dataFatura
!set fatura1.paga := true
!create transportadora1 : Transportadora
!insert (livro1,autor1) into AutorEscreveLivro
!insert (livro1,contrato1) into Contrato_Refere_Livro
!insert (editor1,livro1) into Edita
!insert (livro1,devolucao1) into Solicitacao_Requer_Devolucao_Livro
!set Solicitacao_Requer_Devolucao_Livro1.quantidade := 1
!set Solicitacao_Requer_Devolucao_Livro1.motivo := 'defeito'
!insert (livro1,entrega1) into Entrega_Inclui_Livro
!set Entrega_Inclui_Livro1.quantidade_entregue := 2
!insert (livro1,pedido1) into Pedido_Contem_Livro
!set Pedido_Contem_Livro1.quantidade := 2
!insert (livro1,grafica1) into Grafica_Imprime_Livro
!set Grafica_Imprime_Livro1.cotacao := 0.2
!insert (livro1,grafica1) into Grafica_Cota_Livro
!set Grafica_Cota_Livro1.cotacao := 0.2
!insert (autor1,contrato1) into Autor_Assina_Contrato
!set Autor_Assina_Contrato1.taxa_direitos_autorais_desse_autor := 0.1
!insert (entrega1,pedido1) into Entrega_PedidoCompra
!insert (entrega1,transportadora1) into Transportadora_Faz_Entrega
!insert (entrega1,fatura1) into Entrega_Origina_Fatura
!insert (devolucao1,livreiro1) into Livreiro_Faz_Solicitacao_Devolucao
!insert (livreiro1,transportadora1) into Transportadora_Custa_Para_Livreiro
!set Transportadora_Custa_Para_Livreiro1.custo_frete := 20
!insert (livreiro1,pagamento1) into Livreiro_Faz_Pagamento
!insert (pagamento1,fatura1) into Pagamento_Inclui_Fatura
